### ISSUE TITLE
ALLOW_ERRORS for certain checks (old projects)

### ISSUE THREAD

**Issue by luukverhoeven** [LdesignMedia/gitlab-ci#1]
@hamzatamyachte

Can we add flags to allow errors, for example (not correct syntax):

```yml
{{ALLOW_ERRORS_PHPCPD}}
    - moodle-plugin-ci phpcpd || true
{{ELSE}}
    - moodle-plugin-ci phpcpd
{{/ALLOW_ERRORS_PHPCPD}}
```
Something like a var "ALLOW_ERRORS_PHPCPD=true" by default everything should be strict.

**Comment by hamzatamyachte** [comment]
@luukverhoeven The idea have been implemented!
